language: python
python: 3.6
sudo: enabled
before_install:
- sudo apt-get update
- sudo apt-get install -y git
- sudo apt-get install -y curl
install:
- pip3 install -e .
- pip3 install pytest
- pip3 install responses
- pip3 install coverage
- pip3 install codecov
- pip3 install flake8
script:
- make lint
- make coverage
after_success:
- codecov
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on: 
    branch: master
