language: python

python:
    - 3.6

sudo: enabled
before_install:
 - sudo apt-get update
 - sudo apt-get install -y git
 - sudo apt-get install -y python3 python3-dev python3-pip
 - sudo apt-get install -y curl

# install dependencies
install:
  - pip3 install -e .
  - pip3 install pytest
  - pip3 install responses
  - pip3 install coverage
  - pip3 install codecov
  - pip3 install flake8

script:
  #PEP 8
  - flake8 --ignore=F811 flask_opa.py --count
  #Tests and Coverage
  - coverage erase
  - coverage run -m pytest -v

after_success:
  - codecov